### ISSUE TITLE
date knob passes timestamp (number) instead of Date object

### ISSUE THREAD

**Issue by jardakotesovec** [storybook-eol/storybook-addon-knobs#68]
Is that intention? I would expect that inside component I will receive Date object and not timestamp.

**Comment by simon360** [comment]
It would be nice to have options here. I'd prefer to receive the date as an ISO8601 string, because of the way our component will be used. I'm not sure there's one correct type.

Perhaps an optional callback on `date()` which receives a `Date` as its input and returns whatever it wants, which is then passed on to the component. Could be a string, could be the `Date`, could be the timestamp. The current behaviour would remain as the default.
