### ISSUE TITLE
select knob for optional prop

### ISSUE THREAD

**Issue by alex-bezek** [storybook-eol/storybook-addon-knobs#85]
I am trying to implement a story book for a react component with a number of optional props that `PropTypes.oneOf(['option1', 'option2', 'option3'])`

I would like to be able to configure this knob so by default it doesn't pass in the prop. Is this possible and I'm missing an explanation?

Thanks!

**Comment by bluetidepro** [comment]
I don't know if there is a more graceful way to do this @alex-bezek, but the way I have done this in the past is by doing:

```
{select('BLAH Prop', {
	Value1: 'Name for Value 1 in Select',
	Value2: 'Name for Value 2 in Select',
	'': 'Null',
}, '')}
```

And then that way by default it passes `''` (you could make this `null` if needed) and that's basically the same as passing no prop.

Hope that helps some.

**Comment by Djspaceg** [comment]
An alternative that I do occasionally is this:
```
    propName={select('propName', [null, 'option1', 'option2', 'option3'])}
```
Knobs interprets this `null` as `{'': 'null'}` so your component gets handed a `propName` with an empty string as its value.

Your propTypes can then look like this if you want to make Storybook Knobs happy:
```
    PropTypes.oneOf(['option1', 'option2', 'option3', ''])
```

It would be great if knobs could interpret having a literal `null`, supplied via an Array, as a literal `null` for a prop, by either excluding the prop altogether from the component or sending `null` as the value. Obviously, this isn't as straightforward if you need to supply a hash to the knob since `null` can't be a key, but it would still be nice for an Array.
